import type { RequestHandler } from "express";
import { z } from "zod";
import { supabase } from "../lib/supabase.js";

const schema=z.object({name:z.string().trim().min(2).max(120),contactPersonName:z.string().trim().min(2).max(120),phone:z.string().trim().regex(/^\d{10}$/),email:z.string().trim().email().max(200),categories:z.array(z.string().trim().min(1).max(80)).min(1).max(10),serviceLocations:z.array(z.string().trim().min(1).max(120)).min(1).max(20),teamSizeBand:z.enum(["2-5","6-15","15+"]),businessRegistrationNumber:z.string().trim().max(100).optional().default(""),logoUrl:z.string().url().max(1000).optional().or(z.literal("")).default(""),description:z.string().trim().max(2000).default("")});
const getAgencyUser=async(req:Parameters<RequestHandler>[0])=>{const authorization=req.headers.authorization;if(!authorization?.startsWith("Bearer "))throw new Error("UNAUTHORIZED");const token=authorization.slice("Bearer ".length);const {data,error}=await supabase.auth.getUser(token);if(error||!data.user)throw new Error("UNAUTHORIZED");if(data.user.user_metadata?.role!=="agency")throw new Error("FORBIDDEN");return data.user};
export const handleRegisterAgency:RequestHandler=async(req,res)=>{try{const user=await getAgencyUser(req);const parsed=schema.safeParse(req.body);if(!parsed.success)return res.status(400).json({message:"Please check the agency details and try again.",errors:parsed.error.flatten().fieldErrors});const {data:existing}=await supabase.from("agencies").select("id").eq("user_id",user.id).maybeSingle();const payload={user_id:user.id,name:parsed.data.name,contact_person_name:parsed.data.contactPersonName,phone:parsed.data.phone,email:parsed.data.email,categories:parsed.data.categories,service_locations:parsed.data.serviceLocations,location:parsed.data.serviceLocations.join(", "),team_size_band:parsed.data.teamSizeBand,business_registration_number:parsed.data.businessRegistrationNumber||null,logo_url:parsed.data.logoUrl||null,description:parsed.data.description,updated_at:new Date().toISOString()};const query=existing?.id?supabase.from("agencies").update(payload).eq("id",existing.id).select().single():supabase.from("agencies").insert(payload).select().single();const {data,error}=await query;if(error)throw error;return res.status(existing?.id?200:201).json({agency:data})}catch(error){const code=error instanceof Error?error.message:"";const status=code==="UNAUTHORIZED"?401:code==="FORBIDDEN"?403:500;return res.status(status).json({message:status===500?"Unable to save agency registration.":"Your login session is invalid or expired."})}};
export const handleGetMyAgency:RequestHandler=async(req,res)=>{try{const user=await getAgencyUser(req);const {data,error}=await supabase.from("agencies").select("id,name,contact_person_name,phone,email,categories,service_locations,team_size_band,business_registration_number,logo_url,location,services,description,verified,created_at,updated_at").eq("user_id",user.id).maybeSingle();if(error)throw error;return res.json({agency:data})}catch(error){const code=error instanceof Error?error.message:"";const status=code==="UNAUTHORIZED"?401:code==="FORBIDDEN"?403:500;return res.status(status).json({message:status===500?"Unable to load agency profile.":"Your login session is invalid or expired."})}};
export const handleGetAgencies:RequestHandler=async(req,res)=>{try{const service=String(req.query.service||"").trim().toLowerCase(),location=String(req.query.location||"").trim().toLowerCase();let query=supabase.from("agencies").select("id,name,categories,service_locations,team_size_band,logo_url,description,verified").order("created_at",{ascending:false}).limit(50);const {data,error}=await query;if(error)throw error;const agencies=(data||[]).filter(a=>(!service||(a.categories||[]).some((c:string)=>c.toLowerCase().includes(service)))&&(!location||(a.service_locations||[]).some((l:string)=>l.toLowerCase().includes(location))));const ids=agencies.map(a=>a.id);const {data:workers}=ids.length?await supabase.from("workers").select("id,name,phone,category,locality,experience,initials,tone,about,services,photo_url,available_today,phone_verified,agency_id").in("agency_id",ids):{data:[]};const counts=new Map<string,number>();for(const w of workers||[])counts.set(w.agency_id,(counts.get(w.agency_id)||0)+1);return res.json({agencies:agencies.map(a=>({...a,worker_count:counts.get(a.id)||0})),workers:workers||[]})}catch(error){return res.status(500).json({message:error instanceof Error?error.message:"Unable to load agencies."})}};
export const handleGetAgencyTeam:RequestHandler=async(req,res)=>{try{const id=String(req.params.id||"");if(!id)return res.status(400).json({message:"Agency id is required."});const {data:agency,error}=await supabase.from("agencies").select("id,name,categories,service_locations,team_size_band,logo_url,description,verified").eq("id",id).maybeSingle();if(error)throw error;if(!agency)return res.status(404).json({message:"Agency not found."});const {data:workers,error:workersError}=await supabase.from("workers").select("id,name,phone,category,locality,experience,initials,tone,about,services,photo_url,available_today,phone_verified").eq("agency_id",id);if(workersError)throw workersError;return res.json({agency,workers:workers||[]})}catch(error){return res.status(500).json({message:error instanceof Error?error.message:"Unable to load agency team."})}};
