import { useEffect, useMemo, useState } from "react";
import { BadgeCheck, Building2, Check, Clipboard, Copy, LogOut, MapPin, MessageCircle, Phone, Users, Wrench } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import PageShell from "@/components/PageShell";
import { supabase } from "@/lib/supabase";

type Worker={id:string;name:string;category:string;locality:string;initials:string;photo_url?:string|null;phone_verified:boolean;contact_events_count:number};
type Agency={id:string;name:string;phone:string;email:string;location:string;categories:string[];service_locations:string[];team_size_band:string;verified:boolean;description:string;agency_code?:string;logo_url?:string|null};
type Callback={id:string;worker_id:string;client_name:string;client_phone:string;service_needed:string;preferred_time:string;notes?:string|null;created_at:string;status:"new"|"contacted"|"closed"};
type Dashboard={agency:Agency;workers:Worker[];stats:{linkedWorkers:number;whatsappClicks7d:number;callbacks7d:number};callbacks:Callback[]};

const card="rounded-[18px] border border-black/10 bg-white/70 p-6 dark:border-white/10 dark:bg-white/[0.055]";
const muted="text-slate dark:text-slate-300";

export default function AgencyDashboard(){
 const navigate=useNavigate();
 const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [copied,setCopied]=useState(""); const [updating,setUpdating]=useState<string|null>(null);
 const load=async()=>{if(!supabase){setError("Agency portal is unavailable.");setLoading(false);return}const {data}=await supabase.auth.getSession();const session=data.session;if(!session||session.user.user_metadata?.role!=="agency"){navigate("/login",{replace:true});return}const r=await fetch("/api/agencies/dashboard",{headers:{Authorization:`Bearer ${session.access_token}`},cache:"no-store"});const result=await r.json().catch(()=>null);if(!r.ok){setError(result?.message||"Unable to load agency dashboard.");setLoading(false);return}setDashboard(result);setLoading(false)};
 useEffect(()=>{void load()},[navigate]);
 const copy=async(kind:string,value:string)=>{try{await navigator.clipboard.writeText(value);setCopied(kind);window.setTimeout(()=>setCopied(""),1600)}catch{setError("Copy failed. Please copy the value manually.")}};
 const updateStatus=async(id:string,status:Callback["status"])=>{if(!supabase)return;const {data}=await supabase.auth.getSession();if(!data.session)return;setUpdating(id);try{const r=await fetch(`/api/agencies/callbacks/${id}`,{method:"PATCH",headers:{Authorization:`Bearer ${data.session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({status})});const result=await r.json().catch(()=>null);if(!r.ok)throw new Error(result?.message||"Unable to update callback.");setDashboard(d=>d?{...d,callbacks:d.callbacks.map(c=>c.id===id?{...c,status}:c)}:d)}catch(e){setError(e instanceof Error?e.message:"Unable to update callback.")}finally{setUpdating(null)}};
 const shareUrl=dashboard?.agency.agency_code?`${window.location.origin}/join?ref=${dashboard.agency.agency_code}`:"";
 const pending=useMemo(()=>dashboard?.callbacks.filter(c=>c.status!=="closed").length||0,[dashboard]);
 if(loading)return <PageShell hideBack hideHome><section className={card}><p className={`text-center text-sm ${muted}`}>Loading agency portal...</p></section></PageShell>;
 return <PageShell hideBack hideHome><div className="mx-auto max-w-[1000px] space-y-5">
  {error&&<section className="rounded-[14px] border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</section>}
  {dashboard&&<>
   <section className={card}><div className="flex flex-wrap items-center gap-4"><div className="flex h-14 w-14 items-center justify-center overflow-hidden rounded-2xl bg-primary text-primary-foreground">{dashboard.agency.logo_url?<img src={dashboard.agency.logo_url} alt="" className="h-full w-full object-cover"/>:<Building2 size={27}/>}</div><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-widest text-primary">Agency Portal</p><div className="mt-1 flex flex-wrap items-center gap-2"><h1 className="text-2xl font-extrabold text-foreground">{dashboard.agency.name}</h1>{dashboard.agency.verified&&<span className="inline-flex items-center gap-1 rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700 dark:bg-blue-950/30 dark:text-blue-300"><BadgeCheck size={14}/>Verified</span>}</div><p className={`mt-1 flex items-center gap-1 text-sm ${muted}`}><MapPin size={14}/>{dashboard.agency.service_locations?.join(", ")||dashboard.agency.location}</p></div><Link to="/register-agency" className="rounded-xl border border-border px-4 py-2 text-sm font-bold text-foreground">Edit agency profile</Link></div></section>
   <section className="rounded-[18px] border-2 border-primary bg-card p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Invite workers</p><h2 className="mt-1 text-xl font-extrabold text-foreground">Share your agency code</h2><p className={`mt-1 text-sm ${muted}`}>Workers join themselves using this code or the shareable link.</p></div><div className="rounded-full bg-primary/10 px-3 py-1 text-xs font-extrabold text-primary">{dashboard.stats.linkedWorkers} linked</div></div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto_auto]"><div className="flex items-center justify-center rounded-xl border border-border bg-background px-4 py-4 text-2xl font-black tracking-[0.16em] text-foreground">{dashboard.agency.agency_code||"—"}</div><button type="button" onClick={()=>copy("code",dashboard.agency.agency_code||"")} className="flex h-12 items-center justify-center gap-2 rounded-xl border border-border px-4 font-bold text-foreground"><Copy size={16}/>{copied==="code"?<><Check size={16}/>Copied</>:"Copy code"}</button><button type="button" onClick={()=>copy("link",shareUrl)} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-primary px-4 font-bold text-primary-foreground"><Clipboard size={16}/>{copied==="link"?<><Check size={16}/>Copied</>:"Copy join link"}</button></div><p className={`mt-3 break-all text-xs ${muted}`}>{shareUrl}</p></section>
   <section className="grid gap-3 sm:grid-cols-3"><div className={card}><p className={`text-xs ${muted}`}>Linked workers</p><p className="mt-1 text-3xl font-black text-foreground">{dashboard.stats.linkedWorkers}</p><p className={`mt-1 text-xs ${muted}`}>Current roster</p></div><div className={card}><p className={`text-xs ${muted}`}>WhatsApp clicks</p><p className="mt-1 text-3xl font-black text-foreground">{dashboard.stats.whatsappClicks7d}</p><p className={`mt-1 text-xs ${muted}`}>Last 7 days</p></div><div className={card}><p className={`text-xs ${muted}`}>Callback requests</p><p className="mt-1 text-3xl font-black text-foreground">{dashboard.stats.callbacks7d}</p><p className={`mt-1 text-xs ${muted}`}>Last 7 days</p></div></section>
   <section className={card}><div className="flex items-center justify-between gap-3"><div><h2 className="font-extrabold text-foreground">Team roster</h2><p className={`mt-1 text-xs ${muted}`}>View-only worker roster and existing contact activity.</p></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-extrabold text-primary">{dashboard.workers.length} workers</span></div>{dashboard.workers.length?<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className={`border-b border-border text-xs ${muted}`}><th className="px-3 py-3">Worker</th><th className="px-3 py-3">Category</th><th className="px-3 py-3">Phone</th><th className="px-3 py-3">WhatsApp clicks</th><th className="px-3 py-3">Profile</th></tr></thead><tbody>{dashboard.workers.map(w=><tr key={w.id} className="border-b border-border/70 last:border-0"><td className="px-3 py-3"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center overflow-hidden rounded-full bg-muted text-xs font-bold">{w.photo_url?<img src={w.photo_url} alt="" className="h-full w-full object-cover"/>:w.initials}</span><div><p className="font-bold text-foreground">{w.name}</p><p className={`text-xs ${muted}`}>{w.locality}</p></div></div></td><td className="px-3 py-3 text-foreground">{w.category||"—"}</td><td className="px-3 py-3">{w.phone_verified?<span className="rounded-full bg-green-50 px-2 py-1 text-xs font-bold text-green-700">Verified</span>:<span className={`text-xs ${muted}`}>Not verified</span>}</td><td className="px-3 py-3 font-bold text-foreground">{w.contact_events_count}</td><td className="px-3 py-3"><Link to={`/worker?worker=${encodeURIComponent(w.id)}`} className="text-xs font-bold text-primary">View</Link></td></tr>)}</tbody></table></div>:<div className={`mt-4 rounded-xl border border-dashed border-border p-7 text-center text-sm ${muted}`}>No workers linked yet. Share your agency code to invite workers.</div>}</section>
   <section className={card}><div className="flex items-center justify-between gap-3"><div><h2 className="font-extrabold text-foreground">Callback requests</h2><p className={`mt-1 text-xs ${muted}`}>Requests for workers linked to this agency only.</p></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-extrabold text-primary">{pending} open</span></div>{dashboard.callbacks.length?<div className="mt-4 space-y-3">{dashboard.callbacks.map(c=><div key={c.id} className="rounded-xl border border-border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold text-foreground">{c.client_name}</p><p className={`mt-1 text-xs ${muted}`}>{c.service_needed} · {c.preferred_time}</p><p className={`mt-1 flex items-center gap-1 text-xs ${muted}`}><Phone size={13}/>{c.client_phone}</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-bold capitalize text-foreground">{c.status}</span></div>{c.notes&&<p className={`mt-3 rounded-lg bg-muted/40 p-3 text-xs ${muted}`}>{c.notes}</p>}<div className="mt-3 flex flex-wrap items-center gap-2"><span className={`mr-auto text-xs ${muted}`}>{new Date(c.created_at).toLocaleString()}</span>{c.status!=="contacted"&&<button disabled={updating===c.id} onClick={()=>void updateStatus(c.id,"contacted")} className="rounded-lg border border-border px-3 py-2 text-xs font-bold text-foreground disabled:opacity-50">Mark contacted</button>}{c.status!=="closed"&&<button disabled={updating===c.id} onClick={()=>void updateStatus(c.id,"closed")} className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground disabled:opacity-50">Resolve</button>}</div></div>)}</div>:<div className={`mt-4 rounded-xl border border-dashed border-border p-7 text-center text-sm ${muted}`}>No callback requests yet.</div>}</section>
   <section className={card}><h2 className="font-extrabold text-foreground">Agency details</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-border p-4"><p className={`text-xs ${muted}`}>Phone</p><p className="mt-1 flex items-center gap-2 font-bold text-foreground"><Phone size={14}/>{dashboard.agency.phone}</p></div><div className="rounded-xl border border-border p-4"><p className={`text-xs ${muted}`}>Team size</p><p className="mt-1 flex items-center gap-2 font-bold text-foreground"><Users size={14}/>{dashboard.agency.team_size_band}</p></div><div className="rounded-xl border border-border p-4"><p className={`text-xs ${muted}`}>Categories</p><p className="mt-1 flex items-center gap-2 font-bold text-foreground"><Wrench size={14}/>{dashboard.agency.categories?.join(", ")||"Not added yet"}</p></div></div></section>
   <button onClick={async()=>{await supabase?.auth.signOut();navigate("/",{replace:true})}} className="flex w-full items-center justify-center gap-2 rounded-xl border border-red-200 bg-red-50 p-3 font-bold text-red-700"><LogOut size={17}/>Log out</button>
  </>}
 </div></PageShell>;
}
