import { useEffect, useState } from "react";
import { Building2, LogOut, MapPin, Phone, Wrench } from "lucide-react";
import { useNavigate } from "react-router-dom";
import PageShell from "@/components/PageShell";
import { supabase } from "@/lib/supabase";

type Agency = { name:string; phone:string; email:string; location:string; services:string; description:string };
export default function AgencyDashboard(){
 const navigate=useNavigate(); const [agency,setAgency]=useState<Agency|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{if(!supabase){setError("Agency portal is unavailable.");setLoading(false);return;}const {data}=await supabase.auth.getSession();const session=data.session;if(!session||session.user.user_metadata?.role!=="agency"){navigate("/login",{replace:true});return;}const r=await fetch("/api/agencies/me",{headers:{Authorization:`Bearer ${session.access_token}`},cache:"no-store"});const result=await r.json().catch(()=>null);if(!r.ok) setError(result?.message||"Unable to load agency profile."); else setAgency(result?.agency||null);setLoading(false);})();},[navigate]);
 const logout=async()=>{await supabase?.auth.signOut();navigate("/",{replace:true});};
 if(loading)return <PageShell hideBack hideHome><section className="rounded-[18px] border border-line bg-white p-8 text-center dark:border-white/10 dark:bg-black"><p className="text-sm text-slate dark:text-slate-300">Loading agency portal...</p></section></PageShell>;
 return <PageShell hideBack hideHome><div className="mx-auto max-w-[760px] space-y-5">{error?<section className="rounded-[18px] border border-red-200 bg-red-50 p-6 text-red-700">{error}</section>:agency?<><section className="rounded-[20px] border border-black/10 bg-white/70 p-6 shadow-sm dark:border-white/10 dark:bg-white/[0.055]"><div className="flex items-center gap-4"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-navy text-white"><Building2 size={27}/></div><div><p className="text-xs font-bold uppercase tracking-widest text-slate">Agency Portal</p><h1 className="text-2xl font-extrabold text-navy dark:text-white">{agency.name}</h1><p className="mt-1 flex items-center gap-1 text-sm text-slate"><MapPin size={14}/>{agency.location}</p></div></div></section><section className="rounded-[18px] border border-black/10 bg-white/70 p-6 dark:border-white/10 dark:bg-white/[0.055]"><h2 className="font-extrabold text-navy dark:text-white">Agency details</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-black/10 p-4 dark:border-white/10"><p className="text-xs text-slate">Phone</p><p className="mt-1 flex items-center gap-2 font-bold text-navy dark:text-white"><Phone size={14}/>{agency.phone}</p></div><div className="rounded-xl border border-black/10 p-4 dark:border-white/10"><p className="text-xs text-slate">Services</p><p className="mt-1 flex items-center gap-2 font-bold text-navy dark:text-white"><Wrench size={14}/>{agency.services||"Not added yet"}</p></div></div>{agency.description&&<div className="mt-3 rounded-xl border border-black/10 p-4 dark:border-white/10"><p className="text-xs text-slate">About</p><p className="mt-1 text-sm text-navy dark:text-white">{agency.description}</p></div>}</section><button onClick={logout} className="flex w-full items-center justify-center gap-2 rounded-xl border border-red-200 bg-red-50 p-3 font-bold text-red-700"><LogOut size={17}/> Log out</button></>:null}</div></PageShell>;
}
