import { useEffect, useState } from "react";
import { CheckCircle2, Circle, ShieldCheck, UserRound } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import PageShell from "@/components/PageShell";
import { supabase } from "@/lib/supabase";

export default function ProfileCompleteness(){
 const navigate=useNavigate();const [user,setUser]=useState<any>(null);const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getUser().then(({data})=>{if(!data.user){navigate("/login",{replace:true});return}setUser(data.user);setLoading(false)})},[navigate]);
 if(loading)return <PageShell hideBack hideHome><div className="rounded-[16px] border border-line bg-white p-8 text-center dark:border-white/10 dark:bg-[#151515]">Loading profile...</div></PageShell>;
 if(!user)return null;const m=user.user_metadata||{};const checks=[{label:"Name",done:Boolean(m.name)},{label:"Work category",done:Boolean(m.category)},{label:"Location / area",done:Boolean(m.location)},{label:"About / description",done:Boolean(m.about)},{label:"Services",done:Array.isArray(m.services)?m.services.length>0:Boolean(m.services)},{label:"Profile photo",done:Boolean(m.avatar_url)},{label:"Phone number",done:Boolean(user.phone||m.phone)}];const complete=checks.filter(c=>c.done).length;const percent=Math.round(complete/checks.length*100);const phoneVerified=Boolean(user.phone&&user.phone_confirmed_at);
 return <PageShell backTo={m.role==="worker"?"/worker-dashboard":"/profile"} backLabel="Back"><section className="rounded-[18px] border border-line bg-white p-5 shadow-sm dark:border-white/10 dark:bg-[#151515] sm:p-7"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-teal/10 text-teal"><UserRound size={22}/></div><div className="min-w-0 flex-1"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-teal">Profile quality</p><h1 className="mt-1 text-[28px] font-extrabold tracking-tight text-navy dark:text-white">Profile completeness</h1><p className="mt-1 text-sm text-slate dark:text-slate-300">A complete profile gives people more information before they contact you.</p></div><span className="text-lg font-extrabold text-teal">{percent}%</span></div><div className="mt-5 h-2.5 overflow-hidden rounded-full bg-slate-100 dark:bg-white/10"><div className="h-full rounded-full bg-teal transition-all" style={{width:`${percent}%`}}/></div><div className="mt-5 space-y-2">{checks.map(c=><div key={c.label} className="flex items-center gap-3 rounded-[10px] border border-line px-3 py-2.5 dark:border-white/10"><span>{c.done?<CheckCircle2 size={18} className="text-teal"/>:<Circle size={18} className="text-slate-400"/>}</span><span className="text-sm font-semibold text-navy dark:text-white">{c.label}</span><span className="ml-auto text-xs font-bold text-slate dark:text-slate-400">{c.done?"Complete":"Add this"}</span></div>)}</div><div className="mt-5 flex items-center gap-3 rounded-[12px] border border-line bg-slate-50 px-4 py-3 dark:border-white/10 dark:bg-white/5"><ShieldCheck size={20} className={phoneVerified?"text-teal":"text-slate-400"}/><div><p className="text-sm font-extrabold text-navy dark:text-white">{phoneVerified?"Phone Verified":"Phone verification"}</p><p className="text-xs text-slate dark:text-slate-400">{phoneVerified?"Your phone is verified by your account provider.":"A verification badge appears only after the account phone is actually confirmed."}</p></div></div><Link to="/profile" className="mt-5 inline-flex rounded-[10px] bg-teal px-4 py-2.5 text-sm font-bold text-white">Edit profile</Link></section></PageShell>;
}
