import { useEffect, useState } from "react";
import { Clock3, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import PageShell from "@/components/PageShell";
import { workers as staticWorkers, type Worker } from "@/data/workers";
import type { WorkersResponse } from "@shared/api";
import { getRecentlyViewedWorkerIds, clearRecentlyViewedWorkers } from "@/lib/recently-viewed";

export default function RecentlyViewed() {
  const [workers, setWorkers] = useState<Worker[]>(staticWorkers);
  const [ids, setIds] = useState<string[]>(getRecentlyViewedWorkerIds);
  useEffect(() => { let mounted = true; fetch("/api/workers", { cache: "no-store" }).then(r => r.ok ? r.json() as Promise<WorkersResponse> : Promise.reject()).then(data => { if (mounted) setWorkers(data.workers); }).catch(() => {}); const refresh = () => setIds(getRecentlyViewedWorkerIds()); window.addEventListener("recently-viewed-changed", refresh); return () => { mounted = false; window.removeEventListener("recently-viewed-changed", refresh); }; }, []);
  const viewed = ids.map(id => workers.find(w => w.id === id)).filter((w): w is Worker => Boolean(w));
  return <PageShell backTo="/" backLabel="Home"><section className="rounded-[16px] border border-[#dcece7] bg-[#edf7f3] px-5 py-7 dark:border-white/10 dark:bg-[#151515] sm:px-8 sm:py-9"><div className="flex items-center justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-teal dark:text-[#bdbdbd]">Your activity</p><h1 className="mt-2 text-[30px] font-extrabold tracking-[-0.045em] text-navy dark:text-white">Recently Viewed</h1><p className="mt-2 text-sm text-slate dark:text-slate-300">The workers whose profiles you viewed most recently.</p></div>{viewed.length > 0 && <button type="button" onClick={() => { clearRecentlyViewedWorkers(); setIds([]); }} className="inline-flex shrink-0 items-center gap-2 rounded-[9px] border border-line bg-white px-3 py-2 text-xs font-bold text-slate dark:border-white/10 dark:bg-[#222] dark:text-white"><Trash2 size={14}/>Clear</button>}</div></section><section className="pt-7">{viewed.length ? <div className="space-y-3">{viewed.map(worker => <Link key={worker.id} to={`/worker?worker=${encodeURIComponent(worker.id)}`} className="flex items-center gap-3.5 rounded-[13px] border border-line bg-white p-4 transition hover:shadow-sm dark:border-white/10 dark:bg-[#151515]"><span className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-full bg-[#f3f5f4] text-sm font-extrabold text-navy dark:bg-[#222] dark:text-white">{worker.photo_url ? <img src={worker.photo_url} alt={worker.name} className="h-full w-full object-cover"/> : worker.initials}</span><span className="min-w-0 flex-1"><strong className="block text-sm font-extrabold text-navy dark:text-white">{worker.name}</strong><span className="mt-0.5 block text-xs font-bold text-teal dark:text-[#bdbdbd]">{worker.category}</span><span className="mt-1 block text-xs text-slate dark:text-slate-400">{worker.locality} · {worker.experience}</span></span><Clock3 size={17} className="text-slate-400"/></Link>)}</div> : <div className="rounded-[13px] border border-dashed border-line bg-white p-8 text-center dark:border-white/10 dark:bg-[#151515]"><Clock3 className="mx-auto text-slate-400" size={28}/><h2 className="mt-3 font-extrabold text-navy dark:text-white">No recently viewed workers</h2><p className="mt-1 text-sm text-slate dark:text-slate-400">Open a worker profile and it will appear here.</p><Link to="/" className="mt-4 inline-flex rounded-[9px] bg-teal px-4 py-2 text-xs font-bold text-white">Find workers</Link></div>}</section></PageShell>;
}
