import "dotenv/config";
import express from "express";
import cors from "cors";
import { handleGetWorkers, handleRegisterWorker, handleUpdateWorkerAvailability, handleUpdateWorkerPhoto, handleUpdateWorkerProfile } from "./routes/workers";
import { handleGetNotifications, handleMarkNotificationRead, handleWatchWorker } from "./routes/notifications";
import { handleGetWorkerCallbackRequests, handleDeleteWorkerCallbackRequest, handleUpdateWorkerCallbackStatus } from "./routes/callback-requests";
import { handleGetWorkerStats, handleRecordWorkerReferral } from "./routes/growth";
import { handleGetAgencies, handleGetAgencyTeam, handleGetMyAgency, handleRegisterAgency, handleRegenerateAgencyCode, handleJoinAgency, handleGetAgencyDashboard, handleUpdateAgencyCallbackStatus } from "./routes/agencies";
import { handleCompletePhoneVerification } from "./routes/phone-verification";
import { handleGeocode, handleReverseGeocode } from "./routes/maps";
import { handleServiceChat } from "./routes/chat";
export function createServer(){const app=express();app.use(cors());app.use(express.json());app.use(express.urlencoded({extended:true}));app.get("/api/ping",(_req,res)=>res.json({message:process.env.PING_MESSAGE??"ping"}));app.get("/api/maps/geocode",handleGeocode);app.get("/api/maps/reverse-geocode",handleReverseGeocode);app.post("/api/chat",handleServiceChat);app.get("/api/workers",handleGetWorkers);app.post("/api/workers/register",handleRegisterWorker);app.post("/api/workers/profile",handleUpdateWorkerProfile);app.post("/api/workers/photo",handleUpdateWorkerPhoto);app.post("/api/workers/availability",handleUpdateWorkerAvailability);app.post("/api/phone-verification/complete",handleCompletePhoneVerification);app.get("/api/callback-requests",handleGetWorkerCallbackRequests);app.delete("/api/callback-requests/:id",handleDeleteWorkerCallbackRequest);app.patch("/api/callback-requests/:id",handleUpdateWorkerCallbackStatus);app.get("/api/worker-stats",handleGetWorkerStats);app.post("/api/worker-referral",handleRecordWorkerReferral);app.post("/api/notifications/watch",handleWatchWorker);app.get("/api/notifications",handleGetNotifications);app.post("/api/agencies/register",handleRegisterAgency);app.get("/api/agencies/me",handleGetMyAgency);app.get("/api/agencies/dashboard",handleGetAgencyDashboard);app.patch("/api/agencies/callbacks/:id",handleUpdateAgencyCallbackStatus);app.post("/api/agencies/regenerate-code",handleRegenerateAgencyCode);app.post("/api/agencies/join",handleJoinAgency);app.get("/api/agencies",handleGetAgencies);app.get("/api/agencies/:id",handleGetAgencyTeam);return app}
