import { Menu, X, UserRound, LogOut, BriefcaseBusiness, Search, Bell } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

export default function MobileMenu() {
  const navigate = useNavigate();
  const [open, setOpen] = useState(false); const [loggedIn, setLoggedIn] = useState(false); const [role, setRole] = useState<string | null>(null); const [unread, setUnread] = useState(0);
  const load = async () => { if (!supabase) return; const { data } = await supabase.auth.getSession(); const session=data.session; setLoggedIn(!!session); setRole(session?.user?.user_metadata?.role ?? null); if(session?.user?.user_metadata?.role === "employer"){ try { const response=await fetch("/api/notifications",{headers:{Authorization:`Bearer ${session.access_token}`},cache:"no-store"}); if(response.ok){const result=await response.json();setUnread((result.notifications||[]).filter((n:any)=>!n.read_at).length);} } catch {} } else setUnread(0); };
  useEffect(() => { if (!supabase) return; void load(); const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => { void load(); if (!session) { setOpen(false); navigate("/",{replace:true}); } }); return () => listener.subscription.unsubscribe(); }, [navigate]);
  const logout = async () => { await supabase?.auth.signOut(); setOpen(false); navigate("/",{replace:true}); }; const isWorker=role==="worker"; const isEmployer=role==="employer";
  return <div className="relative flex items-center"><button type="button" aria-label={open?"Close menu":"Open menu"} aria-expanded={open} onClick={()=>setOpen(current=>!current)} className="flex h-10 w-10 items-center justify-center rounded-[10px] border border-slate-300 bg-white text-slate-900 shadow-sm dark:border-slate-800 dark:bg-[#050505] dark:text-white">{open?<X size={20} strokeWidth={2.2}/>:<Menu size={21} strokeWidth={2.2}/>}</button>{open&&<nav className="absolute right-0 top-12 z-30 w-56 rounded-[12px] border border-slate-200 bg-white p-2 shadow-lg dark:border-slate-800 dark:bg-[#080808]"><Link to="/" onClick={()=>setOpen(false)} className="flex items-center gap-2 rounded-[9px] px-3 py-3 text-sm font-bold text-navy hover:bg-slate-100 dark:text-white dark:hover:bg-slate-900"><Search size={16}/>Find Workers</Link>{isWorker&&<Link to="/worker-dashboard" onClick={()=>setOpen(false)} className="flex items-center gap-2 rounded-[9px] px-3 py-3 text-sm font-bold text-navy hover:bg-slate-100 dark:text-white dark:hover:bg-slate-900"><BriefcaseBusiness size={16}/>Worker Portal</Link>}{isEmployer&&<Link to="/inbox" onClick={()=>setOpen(false)} className="flex items-center justify-between rounded-[9px] px-3 py-3 text-sm font-bold text-navy hover:bg-slate-100 dark:text-white dark:hover:bg-slate-900"><span className="flex items-center gap-2"><Bell size={16}/>Inbox</span>{unread>0&&<span className="flex h-5 min-w-5 items-center justify-center rounded-full bg-teal px-1.5 text-[10px] font-extrabold text-white">{unread>9?"9+":unread}</span>}</Link>}{loggedIn&&<><Link to="/profile" onClick={()=>setOpen(false)} className="flex items-center gap-2 rounded-[9px] px-3 py-3 text-sm font-bold text-navy hover:bg-slate-100 dark:text-white dark:hover:bg-slate-900"><UserRound size={16}/>Profile</Link><button type="button" onClick={logout} className="flex w-full items-center gap-2 rounded-[9px] px-3 py-3 text-left text-sm font-bold text-navy hover:bg-slate-100 dark:text-white dark:hover:bg-slate-900"><LogOut size={16}/>Logout</button></>}{!loggedIn&&<Link to="/login" onClick={()=>setOpen(false)} className="block rounded-[9px] px-3 py-3 text-sm font-bold text-navy hover:bg-slate-100 dark:text-white dark:hover:bg-slate-900">Login</Link>}</nav>}</div>;
}
