create table if not exists public.contact_events (
  id bigint generated by default as identity primary key,
  worker_id text not null,
  created_at timestamptz not null default now(),
  source text not null default 'whatsapp',
  constraint contact_events_source_check check (source = 'whatsapp')
);

create table if not exists public.callback_requests (
  id bigint generated by default as identity primary key,
  worker_id text not null,
  client_name text not null,
  client_phone text not null,
  service_needed text not null,
  preferred_time text not null,
  notes text,
  created_at timestamptz not null default now(),
  status text not null default 'new',
  constraint callback_requests_phone_check check (client_phone ~ '^[0-9]{10}$'),
  constraint callback_requests_status_check check (status in ('new','contacted','closed'))
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  worker_id text,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

alter table public.workers add column if not exists phone_verified boolean not null default false;
alter table public.contact_events enable row level security;
alter table public.callback_requests enable row level security;
alter table public.analytics_events enable row level security;

grant insert on public.contact_events to anon, authenticated;
grant insert on public.callback_requests to anon, authenticated;
grant insert on public.analytics_events to anon, authenticated;
grant select on public.contact_events to service_role;
grant select, update on public.callback_requests to service_role;
grant select on public.analytics_events to service_role;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='contact_events' and policyname='Anyone can log WhatsApp contact events') then
    create policy "Anyone can log WhatsApp contact events" on public.contact_events for insert to anon, authenticated with check (source = 'whatsapp');
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='callback_requests' and policyname='Anyone can submit callback requests') then
    create policy "Anyone can submit callback requests" on public.callback_requests for insert to anon, authenticated with check (length(trim(client_name)) between 1 and 120 and length(trim(client_phone)) = 10 and length(trim(service_needed)) between 1 and 200 and length(trim(preferred_time)) between 1 and 120 and (notes is null or length(notes) <= 2000));
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='analytics_events' and policyname='Anyone can log analytics events') then
    create policy "Anyone can log analytics events" on public.analytics_events for insert to anon, authenticated with check (length(trim(event_type)) between 1 and 80 and jsonb_typeof(metadata) = 'object');
  end if;
end $$;
